### ISSUE TITLE
Possible enhancements to French?

### ISSUE THREAD

**Issue by LeMoussel** [jdkato/prose#11]
Have you considered adding for French text processing?

**Comment by jdkato** [comment]
Yes, I'd like to support French (among other languages). I'm currently working on adding a multilingual sentence boundary detector, which should be ready relatively soon.

I'd say, eventually, everything but the `summarize` package (which is pretty English-specific) should be multilingual to some degree.

**Comment by jdkato** [comment]
Unfortunately, I don't think this will be happening anytime soon.
