### ISSUE TITLE
Measure readability

### ISSUE THREAD

**Issue by LeMoussel** [jdkato/prose#13]
Is it possible, with Prose, to measure readability like :

- Readability scores -  Flesch-Kincaid, Gunning Fog and the SMOG index.

- Text analytics - like letter, word and syllable counts and composition stats (like adjective, noun and adverb counts)

- Keywork densities

- Sentiment analysis - is the text positive, negative or neutral

**Comment by jdkato** [comment]
The first three are available in the [`summarize`](https://godoc.org/github.com/jdkato/prose/summarize) package. There's a [minimal usage example](https://github.com/jdkato/prose#summarizing-godoc) on the README.
