### ISSUE TITLE
Make it possible to use vendored

### ISSUE THREAD

**Issue by bep** [jdkato/prose#14]
Very useful project.

I wanted to test the title case functionality for use in Hugo, but we vendor our libraries, and I get a `../vendor/github.com/jdkato/prose/transform/title.go:9:2: use of internal package not allowed` when importing `github.com/jdkato/prose/transform`.

See https://github.com/gohugoio/hugo/pull/3753

I have been Googling this, and it seems there is no (simple) workaround other than avoiding the use of `internal` packages in libraries.

**Comment by jdkato** [comment]
Hi,

Yeah, I've definitely be willing to restructure the project to make it more easier to user. However, I think I'd like to understand the issue a little better first.

I vendor (using [`dep`](https://github.com/golang/dep)) prose [in a project](https://github.com/ValeLint/vale) that's pretty similar to Hugo structure-wise, so perhaps the issue is specific to particular vend tool?

**Comment by bep** [comment]
>so perhaps the issue is specific to a particular vendor tool?

I assume `dep` also pulls dependencies to `/vendor` (which is the standard). I will check your project and see if I understand this.

**Comment by bep** [comment]
OK, this works if I also do a:

```
 govendor add github.com/jdkato/prose/internal/util
```

Which I would say works, but require the end user to know a little too much about the `internals` of the project ... And should at least be documented.

**Comment by jdkato** [comment]
Yes, I agree.

If I don't do away with the `internal` package altogether, I'll definitely document it. Although, I imagine the issue exists for a number of similarly-structured projects as well, including those in `golang.org/x/` (e.g., [text](https://godoc.org/golang.org/x/text)).

**Comment by bep** [comment]
>Edit: it looks like you've indeed had to use a similar technique for text?

Yes, but my memory is like a gold fish (and there are other chefs on that project).
