### ISSUE TITLE
CJK support ?

### ISSUE THREAD

**Issue by wenerme** [jdkato/prose#16]
Dose prose support CJK ?

**Comment by wenerme** [comment]
OK, I see `primarily English at the moment`.

Should I keep this issues open before "the moment" past ?

**Comment by jdkato** [comment]
Yes, we can keep this open. Eventually, I'd at least like to have tokenizers and taggers available for other languages.

**Comment by jdkato** [comment]
Unfortunately, I don't think this will be happening anytime soon.
