### ISSUE TITLE
Great work! ...but README example code does not work

### ISSUE THREAD

**Issue by elliott5** [jdkato/prose#2]
I got it working (as a test) with:
```
package pos

import (
	"strings"
	"testing"

	"github.com/jdkato/prose/tag"
)

func TestProse(t *testing.T) {
	text := "A fast and accurate part-of-speech tagger for Golang."

	tagger := tag.NewPerceptronTagger()
	tags := tagger.Tag(strings.Split(string(text), " "))
	for _, tok := range tags {
		t.Log(tok.Text, tok.Tag)
	}
}
```

Great work otherwise :)

**Comment by elliott5** [comment]
But I think you may have fixed the issue while I wrote it up!

**Comment by elliott5** [comment]
All example code on the front page now works for me, so I'm closing the issue.

Looking forward to seeing the text summarisation :]

**Comment by jdkato** [comment]
Oh, yeah, sorry. The README got a much needed update today.

I'll be working on a `summarize` package this week, in which I plan on initially supporting readability (Kincaid, SMOGIndex, etc.) and usage (counts, densities, lengths) statistics.

Thanks for trying out the project!
