### ISSUE TITLE
Portuguese support

### ISSUE THREAD

**Issue by jeffprestes** [jdkato/prose#25]
Hi!

First of all, congratulations! It's very cool project.
How could we help you to include Portuguese support? Which corpus do you use training the dataset?
Do you accept wordnet format? (https://github.com/own-pt/openWordnet-PT)

Kind regards!

**Comment by jdkato** [comment]
Adding support for other languages is something I'd like to do eventually. Unfortunately, it's going to require quite a bit of work -- in particular, tokenization and segmentation (the former of which is relied upon by the tagger and NER) are very English-specific currently. For starters, I'd at least like to support using externally-developed tokenizers and segmenters.

However,  I think there are other areas (namely, documentation and performance) that are more pressing at the moment. So, I'm not sure when I'll get around to thinking about this more.
