### ISSUE TITLE
Prose installation issues

### ISSUE THREAD

**Issue by Hasil-Sharma** [jdkato/prose#28]
I tried installing prose using the command provided `go get gopkg.in/jdkato/prose.v2` and this is the error log printed on my terminal.

```
# gopkg.in/jdkato/prose.v2
../gopkg.in/jdkato/prose.v2/extract.go:323:23: est.AtVec undefined (type *mat.VecDense has no field or method AtVec)
../gopkg.in/jdkato/prose.v2/extract.go:335:25: est.AtVec undefined (type *mat.VecDense has no field or method AtVec)
../gopkg.in/jdkato/prose.v2/extract.go:355:17: count.AtVec undefined (type *mat.VecDense has no field or method AtVec)
../gopkg.in/jdkato/prose.v2/extract.go:525:27: count.AtVec undefined (type *mat.VecDense has no field or method AtVec)
```
go-lang version : `go1.9.7 darwin/amd64`

**Comment by jdkato** [comment]
Can you try running `go get -u gopkg.in/jdkato/prose.v2`?

**Comment by Hasil-Sharma** [comment]
I ran `go get -u gopkg.in/jdkato/prose.v2`. This is the error log I get:

```
package vendor/github.com/montanaflynn/stats: /Users/hasilsharma/git-repo/src/vendor/github.com/montanaflynn/stats/.git exists but is not a directory
package vendor/gonum.org/v1/gonum/mat: /Users/hasilsharma/git-repo/src/vendor/gonum.org/v1/gonum/.git exists but is not a directory
package vendor/gopkg.in/neurosnap/sentences.v1: /Users/hasilsharma/git-repo/src/vendor/gopkg.in/neurosnap/sentences.v1/.git exists but is not a directory
```

**Comment by jdkato** [comment]
I wasn't able to reproduce this. So, assuming you've set up your `$GOPATH` correctly (i.e., you can `go get` other packages), it may be related to https://github.com/golang/go/issues/17522.

If so, it seems like vendoring our dependencies may help (https://github.com/davecheney/httpstat/pull/122).

**Comment by ernsheong** [comment]
The use of gopkg.in isn't the best practice in 2018, perhaps consider the use of direct github repo?
