### ISSUE TITLE
Possible enhancements to the "summarize" package

### ISSUE THREAD

**Issue by elliott5** [jdkato/prose#3]
Have you considered adding the Coleman–Liau index for completeness? Even though "opinion varies on its accuracy": https://en.wikipedia.org/wiki/Coleman%E2%80%93Liau_index

On the subject of suspect measures, a composite "years-of-education" metric, taking the average of scores together (and their standard deviation) may be of use: https://github.com/elliott5/readability/blob/master/assess.go

Finally, for giving feedback to users on how to change their prose to be easier to read, it would be great if your analysis could store:  
- sentences with their word length; and 
- words with their syllable length and frequency (the product of the two ranking non-readability).

Keep up the good work!

**Comment by jdkato** [comment]
I think these are all good ideas and I'll definitely work on implementing them.

Thanks for the input&mdash;I'll update this issue as I make progress.

**Comment by jdkato** [comment]
Just an update on today's progress:

1. I've added the Coleman–Liau index;
2. sentences are now stored as a `map[string]int`, where the key is the sentence and the value is its word length; and
3. words are now stored as a `map[string][]int`, where the key is the word and the value is `[frequency, syllables]`.

Let me know if you have any thoughts on this so far ("years-of-education" is on the way, too).

Thanks!

**Comment by elliott5** [comment]
This is wonderful Joseph, thank you. I'm sorry I've not been as clear-headed about the end-point I'd like to see as I should have been, so here goes with a better explanation:

Given a text, and the various measures of its complexity, I would like to guide the author of that text as to how to simplify it, by highlighting those sentences (and words within those sentences) that contribute most to the complexity score.

As a visualization, I would like to create an HTML fragment showing the text as a heat-map, with the simplest sentences/words in blue and the most complex in red. In this visualization, each sentence would have a background color (including the spaces), then each word would have its own color that was more blue/red than the sentence as a whole. The visualization could be done using any of the measures of complexity, but I'm guessing estimated "years-of-education" would give the richest results.

In order to create such a visualization, one would require, for each sentence:
- the sentence text
- the utf8 offset to the start of that sentence text (or number, if the sentences are contiguous)
- the Assessment{} of that sentence
- for each word:
-- the word text
-- the utf8 offset to the start of that word text (from the start of the sentence or text as a whole)
-- the Assessment{} of that word (calculated as a single word sentence)

The heat map temperature for an individual word would be the addition of its individual Assessment{} with that of the surrounding sentence, obviously all normalized and mapped to colour coding from blue to red. 

I hope this "heat-map" idea is of interest to you.

**Comment by jdkato** [comment]
It's definitely an interesting idea, but I'm not sure that this package alone will be able to meet those needs. Here are a few of my thoughts:

- This package and its underlying calculations (Flesch–Kincaid, Gunning Fog, etc.) expect a unit of text no smaller than a sentence. For example, the Flesch–Kincaid equation includes a fraction of `total words / total sentences`. If we were to calculate this on a single-word sentence, would this be `1 / 1`? Technically, there are zero sentences&mdash;but that's computationally problematic...
- We'd be doing a lot of extra work that not everyone will need. My personal use case for this package is to be able to efficiently calculate these metrics on the *entirety of* (potentially large) documents. In other words, I only need one Assessment per document but I'd be calculating `1 + N sentences + N words` Assessments.

So, from a general-purpose package design standpoint, I think it might make the most sense to keep a narrow focus: take a string as input, tokenize it into the parts necessary for our calculations (i.e., sentences and words), and produce a single Assessment. Does this seem like a reasonable standpoint?

---

In terms of your particular use case, this would mean that you'd need perform a separate tokenization step: 

1. Split your text into sentences, note the offsets, and initialize each sentence as its own `Document`;
2. split each sentence into words, note the offsets, and initialize each word as its own `Document`.

At this point, though, you've lost the benefit of shared internal calculations, which is one of the main differences from the readability package you've linked to above. You're also gaining unnecessary overhead: every time you initialize a `Document`, it's trying to tokenize its input into sentences and words. However, depending on whether you're giving it a sentence or a word, you really only need at most word tokenization.

**Comment by elliott5** [comment]
Yes Joseph, that is a reasonable standpoint. Better to have a fast general-purpose library that everyone can use.

I can then build upon it in the way you describe to achieve the particular visualization I am after.

**Comment by jdkato** [comment]
I've added both a `MeanGradeLevel` and a `StdGradeLevel` to an `Assessment`.

I'm closing this since I think we've now addressed the original concerns. Let me know if I've missed something.

**Comment by elliott5** [comment]
LGTM!

Just a couple of suggestions, for clarity:
- rename `StdGradeLevel` to `StdDevGradeLevel`
- reorder the `Assessment` struct so that `MeanGradeLevel` and `StdDevGradeLevel` are side-by-side

As a separate issue, it would be helpful for a new reader if each of the comments of the various assessment methods linked to the wikipedia entry for it, as I just had to look up https://en.wikipedia.org/wiki/Dale%E2%80%93Chall_readability_formula ... well done for implementing it by-the-way!

I'll maybe create a PR with these changes in...
