### ISSUE TITLE
Is there way to generate the jsonl file using a set of data, OR how do we calculate rank,score,input_has etc for the jsonl file. Please suggest .

### ISSUE THREAD

**Issue by vk18vk** [jdkato/prose#33]
Is there way to generate the jsonl file using a set of data,
OR how do we calculate rank,score,input_has etc for the jsonl file. Please suggest .
Ex: {"text":"This was taken during the Easter celebrations at Real de Catorce, MX.","spans":[{"start":66,"end":68,"text":"MX","rank":0,"label":"PRODUCT","score":0.9525150387,"source":"core_web_sm","input_hash":19964311,"answer":"reject"}],"meta":{"section":"photography","score":0.9525150387},"_input_hash":19964311,"_task_hash":1331479932,"answer":"reject"}
In here i=how do i caluculate score input has and other parameters

**Comment by jdkato** [comment]
Those parameters come from [Prodigy](https://prodi.gy/), but they aren't required for training `prose`. As mentioned in the [tutorial](https://medium.com/@errata.ai/prodigy-prose-radically-efficient-machine-teaching-in-go-93389bf2d772), you only need to provide a slice of [EntityContext](https://godoc.org/gopkg.in/jdkato/prose.v2#EntityContext) structures.

In other words, this would be sufficient:

```json
{
  "text": "This was taken during the Easter celebrations at Real de Catorce, MX.",
  "spans": [
    {
      "start": 66,
      "end": 68,
      "label": "PRODUCT",
    }
  ],
  "accept": true
}
```
