### ISSUE TITLE
Compare spaCy segmentation?

### ISSUE THREAD

**Issue by Xeoncross** [jdkato/prose#42]
Can you add python [spaCy](https://spacy.io/usage/facts-figures) to the [segmenting comparison table](https://github.com/jdkato/prose#segmenting)? As far as I know, their neural network does a great job on splitting sentences correctly and I'd love to see if compared here so I can decide if prose is a good replacement.

**Comment by jdkato** [comment]
I tested spaCy's [`en_core_web_sm` model a while ago](https://www.reddit.com/r/golang/comments/8ze154/prose_v200_a_natural_language_processing_library/e2ie1b3/) and it scored 31 / 52 (0.596).

That said, the test suite is available in an [easy-to-test JSON format](https://github.com/jdkato/prose/blob/v2/testdata/golden_rules_en.json) if you'd like to test an updated (or different) model.
