### ISSUE TITLE
Doccano

### ISSUE THREAD

**Issue by tovare** [jdkato/prose#43]
Hi,

Is it possible to feed data from Doccano into Prose for Named entity ?

https://github.com/chakki-works/doccano

https://github.com/chakki-works/doccano/wiki/Import-and-Export-File-Formats

I read through the Prodigy tutorial, just asking if there are any known pitfalls with Doccano before I start and hit a brick wall :-)

**Comment by tntobias** [comment]
I have done this successfully albiet manually. I had to do a little more work to adapt the doccano output to prose structs but it was pretty much the same procedure as demonstrated in the prodigy tutorial.
