### ISSUE TITLE
How do you solve this problem?

### ISSUE THREAD

**Issue by silencecmsj** [jdkato/prose#46]
Segmenting:
input:Mr. James told me Dr. Brown is not available today. I will try tomorrow.
output:
Mr. James told me Dr.
Brown is not available today.
I will try tomorrow.

**Comment by SikandAlex** [comment]
You gave no detail as to the problem you are trying to solve. You just mention the word 'segmenting'. The title of your issue is also ambiguous and unhelpful. If you can provide more information I'm sure someone here would gladly help you out.
