### ISSUE TITLE
Migrating to Go modules

### ISSUE THREAD

**Issue by Ben-Ackerman** [jdkato/prose#48]
Are there any plans to migrating this project to using go modules?  

The reason I am requesting it is that it would make it easier to manage dependence when contributing.  Additionally since this package doesn't appear to be utilizing any other dependence manager migrating it to a single go module should be a simple change.

**Comment by jdkato** [comment]
Yes, this is something that I'd like to do. 

In the process of doing so, I'd like to also drop `gopkg.in`&mdash;which means we'd need to support [multiple major versions](https://github.com/golang/go/wiki/Modules#v2-modules-allow-multiple-major-versions-within-a-single-build). My understanding is that we'd follow the basis process outlined in [Releasing Modules (v2 or Higher)](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher).

**Comment by titusjaka** [comment]
Would you mind if I grab this issue? :)
