### ISSUE TITLE
Speeding up tokenizer process?

### ISSUE THREAD

**Issue by dimus** [jdkato/prose#51]
We have tasks that involve finding named entities in large volumes of text (billions of pages), and it would be great to use `prose` for our purposes. However, the speed of execution is a problem. One way to optimize performance would be to figure out how to do tokenizing faster. 

We wrote another named entity recognition tool, specialized in finding scientific names, where getting rid of regular expressions helped to reach very fast scanning speeds. Here is an example of our tokenizing solution:  https://github.com/gnames/gnfinder/blob/master/token/tokenize.go#L12

Having much faster tokenizer for `prose` would be a fantastic improvement, and probably would allow us to use it on the scale approaching the whole corpus of published data.

**Comment by jdkato** [comment]
I don't currently have a lot of time to work on this library, but my primary development goals for v3.0.0 are support for custom components (as mentioned in #32) and drop-in support for [spaCy models](https://spacy.io/models). So, eventually, you'll be able to use your own tokenizer if you want.

---

That said, more specifically:

1. I think it's important to understand the difference between writing a tokenizer for a specific purpose and attempting to provide a general solution: As is, the `gnfinder` tokenizer does little more than split on whitespace, which I don't consider to be "good enough" for general usage.

2. I share your view on regular expressions; I think they should be avoided (especially in Go) whenever possible. However, [v2.0.0](https://github.com/jdkato/prose/blob/v2/tokenize.go) makes very little use of them&mdash;so the task of optimization isn't as simple as "stop using regex."

3. These conversations usually aren't very productive without referencing test (see point 1) and benchmark results. Here's a comparison of `gopkg.in/jdkato/prose.v2` (`old`) and `github.com/gnames/gnfinder/token` (`new`) using the [`BenchmarkTokenization`](https://github.com/jdkato/prose/blob/v2/tokenize_test.go#L161) data:

```
goos: darwin
goarch: amd64
pkg: github.com/jdkato/prose
BenchmarkTokenizationProse-8   	      30	  38292473 ns/op	12873334 B/op	   62257 allocs/op
PASS
ok  	github.com/jdkato/prose	1.224s
Success: Benchmarks passed.
```

```
goos: darwin
goarch: amd64
pkg: github.com/jdkato/prose
BenchmarkTokenizationGnFinder-8   	      20	  67860778 ns/op	99116001 B/op	  454391 allocs/op
PASS
ok  	github.com/jdkato/prose	1.500s
Success: Benchmarks passed.
```

```
benchmark                 old ns/op     new ns/op     delta
BenchmarkTokenization     38292473      67860778      +77.22%

benchmark                 old allocs     new allocs     delta
BenchmarkTokenization     62257          454391         +629.86%

benchmark                 old bytes     new bytes     delta
BenchmarkTokenization     12873334      99116001      +669.93%
```
