### ISSUE TITLE
go get not working

### ISSUE THREAD

**Issue by pjebs** [jdkato/prose#57]
I tried to go get the hugo repo. I am using Go 1.14 (with go modules)

`go get github.com/gohugoio/hugo`

```go
package github.com/jdkato/prose/transform: cannot find package "github.com/jdkato/prose/transform" in any of:
	/usr/local/go/src/github.com/jdkato/prose/transform (from $GOROOT)
	/Users/x/GOPATH/src/github.com/jdkato/prose/transform (from $GOPATH)
```

I'm wondering why it is saying `transform` can't be found?

**Comment by xzjkya** [comment]
Can you share your `go env` with us? Since prose is a module you might need `GO111MODULE=on` in it to work depending on how you set up your `GOPATH`.

**Comment by pjebs** [comment]
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/x/Library/Caches/go-build"
GOENV="/Users/x/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/x/GOPATH"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xz/c0bpf45d3c765zg0gth78x7w0000gn/T/go-build415804916=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by xzjkya** [comment]
@pjebs , if I not wrong you can set `GO111MODULE` like this `go env -w GO111MODULE=on`. Run it once and then check if its set with `go env` again. Inside any directory do `go mod init` and try the `go get`. It should work inside and outside your `GOPATH`. Before `GO111MODULE` things were a bit tricky in Go and after it things are trickier than ever lol. Took me a while to understand it. When you're done there should be a `pkg/mod` inside your `GOPATH`. It will have a similar structure as the URI you do a `go get`.

**Comment by pjebs** [comment]
i thought go 1.14 had Go modules on by default

**Comment by xzjkya** [comment]
@pjebs , did it work? Could you close this issue? :-) Oh answering your question sort of and I think that was done in 1.13, but the behavior when that flag is "" is sort of mixed and I think it depends where you place your project related to `GOPATH`. Most projects are migrating to it (its good although it kinda forces you to have a certain project layout) and it will eventually be the default behavior (with no others besides vendoring).
