### ISSUE TITLE
Improper tokenization of word+".\t\n"+word

### ISSUE THREAD

**Issue by elliott5** [jdkato/prose#6]
```
func TestTokErr(t *testing.T) {
	text := `
The recording calls into question evidence given in 2012 to the Treasury select committee by former Barclays boss Bob Diamond and Paul Tucker, the man who went on to become the deputy governor of the Bank of England.	
Libor, the London Interbank Offered Rate, tracks how much it costs banks to borrow money from each other. 
`
	words := tokenize.NewTreebankWordTokenizer().Tokenize(text)
	t.Log(words)
}
```
Yields the token ```"London.\t"```.
Text from: http://www.bbc.co.uk/news/business-39548313 

I note that any trailing "." is always attached to the previous token, rather than given a new token as (for example) "," are. I presume that is to enable proper nouns like "B.B.C." or "Mr. Jones", but I'm not clear why we need the trailing tab.

**Comment by jdkato** [comment]
There are a few things at play here:

1. [`TreebankWordTokenizer`](https://godoc.org/github.com/jdkato/prose/tokenize#TreebankWordTokenizer.Tokenize) expects a single sentence (not raw text) as input.
2. Your use of a string literal.

Here are a few examples from the reference Python implementation:

```python
>>> from nltk.tokenize import TreebankWordTokenizer, sent_tokenize
>>> raw_text = r'this is a sentence.\t\n'
>>> text = 'this is a sentence.\t\n'
>>> sent_tokenize(raw_text)
['this is a sentence.\\t\\n']
>>> sent_tokenize(text)
['this is a sentence.']
>>> tok = TreebankWordTokenizer()
>>> tok.tokenize('this is a sentence.\\t\\n')
['this', 'is', 'a', 'sentence.\\t\\n']
>>> tok.tokenize('this is a sentence.')
['this', 'is', 'a', 'sentence', '.']
```
And here is this library:

```go
package main

import (
	"fmt"

	"github.com/jdkato/prose/tokenize"
)

func main() {
	wTok := tokenize.NewTreebankWordTokenizer()

	sTok := tokenize.NewPunktSentenceTokenizer()
	// NOTE: ^ this is just a wrapper around `neurosnap/sentences` that
	// implements the `ProseTokenizer` interface.

	fmt.Println(sTok.Tokenize(`this is a sentence.\t\n`))
	// [this is a sentence.\t\n], len == 1

	fmt.Println(sTok.Tokenize("this is a sentence.\t\n"))
	// [this is a sentence. \t\n], len == 2

	fmt.Println(wTok.Tokenize(`this is a sentence.\t\n`))
	// [this is a sentence.\t\n]

	fmt.Println(wTok.Tokenize("this is a sentence.\t\n"))
	// [this is a sentence .]
}
```

So, it looks like `TreebankWordTokenizer` is behaving as it should? If you're looking for a more custom tokenizer, I'd recommend using [`RegexpTokenizer`](https://godoc.org/github.com/jdkato/prose/tokenize#RegexpTokenizer).

**Comment by elliott5** [comment]
Sorry, I should have dug around more before creating the issue.
Thank you for long and polite explanation.
At least I'm exploring this excellent repo of yours...

**Comment by jdkato** [comment]
No problem! The testing is much appreciated!
