### ISSUE TITLE
List of Label?

### ISSUE THREAD

**Issue by vitsensei** [jdkato/prose#70]
Hi,
I can see that we have a comprehensive list of tags but can't find anything for label (for example, PERSON, GPE, etc). Would be nice if someone can redirect me to the list, even if it is somewhere in the source code.

**Comment by vitsensei** [comment]
I found this list but not sure if it is 100% matching with ``prose``.

> PERSON:      People, including fictional.
> NORP:        Nationalities or religious or political groups.
> FAC:         Buildings, airports, highways, bridges, etc.
> ORG:         Companies, agencies, institutions, etc.
> GPE:         Countries, cities, states.
> LOC:         Non-GPE locations, mountain ranges, bodies of water.
> PRODUCT:     Objects, vehicles, foods, etc. (Not services.)
> EVENT:       Named hurricanes, battles, wars, sports events, etc.
> WORK_OF_ART: Titles of books, songs, etc.
> LAW:         Named documents made into laws.
> LANGUAGE:    Any named language.
> DATE:        Absolute or relative dates or periods.
> TIME:        Times smaller than a day.
> PERCENT:     Percentage, including ”%“.
> MONEY:       Monetary values, including unit.
> QUANTITY:    Measurements, as of weight or distance.
> ORDINAL:     “first”, “second”, etc.
> CARDINAL:    Numerals that do not fall under another type.

**Comment by nicolasassi** [comment]
[https://github.com/jdkato/prose/blob/master/model/Maxent/labels.gob](url) a decoded this file and found the following labels: 
`labels: [I-GSP B-LOCATION B-GPE I-ORGANIZATION I-PERSON O I-FACILITY I-LOCATION B-PERSON B-FACILITY B-GSP B-ORGANIZATION I-GPE]`

pretty sure those are the default labels used by Prose

**Comment by ptiger10** [comment]
For others who didn't know, the I- and B- prefixes refer to whether the word is (I)nside an existing "chunk" describing a named entity or the (B)eginning of a new chunk. The prefixes are dropped in document.entities (accessed with `doc.Entities()`) but preserved in document.tokens (`doc.Tokens()`). Here is more info on the [inside-outside-beginning scheme](https://en.wikipedia.org/wiki/Inside%E2%80%93outside%E2%80%93beginning_(tagging))
