### ISSUE TITLE
Loading a model from embedded FS

### ISSUE THREAD

**Issue by itzamna314** [jdkato/prose#76]
I'd like to be able to build models, store them as files, and embed them into an application where I can load them up for NER. However, `ModelFromDisk` takes a filepath rather than an `io.FS`, so I need to copy all of my model files alongside my executable instead of embedding them at build time.

Would you consider adding `ModelFromFS(f fs.FS) *Model`, taking an [`fs.FS`](https://pkg.go.dev/io/fs#FS) as input? I could do the implementation if you'd like to add it to the library.

**Comment by jdkato** [comment]
Yes, a PR is welcome.

**Comment by itzamna314** [comment]
🙇 I'll push something up in the next week or 2
